module.exports = [
	{text: "%s would be woefully incomplete without %s2.", pick: 2},
	{text: "After months of debate, the Occupy Wall Street General Assembly could only agree on \"More %s!\"", pick: 1},
	{text: "Before %s, all we had was %s2.", pick: 2},
	{text: "Before I run for president, I must destroy all evidence of my involvement with %s.", pick: 1},
	{text: "Charades was ruined for me forever when my mom had to act out %s.", pick: 1},
	{text: "During his midlife crisis, my dad got really into %s.", pick: 1},
	{text: "Everyone down on the ground! We don't want to hurt anyone. We're just here for %s.", pick: 1},
	{text: "I spent my whole life working toward %s, only to have it ruined by %s2.", pick: 2},
	{text: "I went from %s to %s2, all thanks to %s3.", pick: 3, draw: 2},
	{text: "If God didn't want us to enjoy %s, he wouldn't have given us %s2.", pick: 2},
	{text: "In his newest and most difficult stunt, David Blaine must escape from %s.", pick: 1},
	{text: "Little Miss Muffet Sat on a tuffet, Eating her curds and %s.", pick: 1},
	{text: "Members of New York's social elite are paying thousands of dollars just to experience %s.", pick: 1},
	{text: "My country, 'tis of thee, sweet land of %s.", pick: 1},
	{text: "My mom freaked out when she looked at my browser history and found %s.com/%s2.", pick: 2},
	{text: "My new favorite porn star is Joey \"%s\" McGee.", pick: 1},
	{text: "Next time on Dr. Phil: How to talk to your child about %s.", pick: 1},
	{text: "Only two things in life are certain: death and %s.", pick: 1},
	{text: "The Five Stages of Grief: denial, anger, bargaining, %s, acceptance.", pick: 1},
	{text: "The healing process began when I joined a support group for victims of %s.", pick: 1},
	{text: "The votes are in, and the new high school mascot is %s.", pick: 1},
	{text: "This is your captain speaking. Fasten your seatbelts and prepare for %s.", pick: 1},
	{text: "This month's Cosmo: \"Spice up your sex life by bringing %s into the bedroom.\"", pick: 1},
	{text: "Tonight on 20/20: What you don't know about %s could kill you.", pick: 1},
	{text: "You haven't truly lived until you've experienced %s and %s2 at the same time.", pick: 2}
];