module.exports = [
	{text: 'A 55-gallon drum of lube'},
	{text: 'A bigger, blacker dick'},
	{text: 'A Burmese tiger pit'},
	{text: 'A dollop of sour cream'},
	{text: 'A magic hippie love cloud'},
	{text: 'A man in yoga pants with a ponytail and feather earrings'},
	{text: 'A piñata full of scorpions'},
	{text: 'A sad fat dragon with no friends'},
	{text: 'A slightly shittier parallel universe'},
	{text: 'A soulful rendition of "Ol\' Man River."'},
	{text: 'A squadron of moles wearing aviator goggles'},
	{text: 'A sweaty, panting leather daddy'},
	{text: 'A sweet spaceship'},
	{text: 'All of this blood'},
	{text: 'An army of skeletons'},
	{text: 'An ether-soaked rag'},
	{text: 'An unhinged ferris wheel rolling toward the sea'},
	{text: 'Another shot of morphine'},
	{text: 'Basic human decency'},
	{text: 'Beefin\' over turf'},
	{text: 'Being awesome at sex'},
	{text: 'Boris the Soviet Love Hammer'},
	{text: 'Bullshit'},
	{text: 'Catastrophic urethral trauma'},
	{text: 'Daddy\'s belt'},
	{text: 'Death by Steven Seagal'},
	{text: 'Dining with cardboard cutouts of the cast of \"Friends.\"'},
	{text: 'Double penetration'},
	{text: 'Existing'},
	{text: 'Fetal alcohol syndrome'},
	{text: 'Finding Waldo'},
	{text: 'Fuck Mountain'},
	{text: 'Getting hilariously gang-banged by the Blue Man Group'},
	{text: 'Grandpa\'s ashes'},
	{text: 'Graphic violence, adult language, and some sexual content'},
	{text: 'Hillary Clinton\'s death stare'},
	{text: 'Intimacy problems'},
	{text: 'Jeff Goldblum'},
	{text: 'Living in a trashcan'},
	{text: 'Loki, the trickster god'},
	{text: 'Making a friend'},
	{text: 'Me'},
	{text: 'Mild autism'},
	{text: 'Mooing'},
	{text: 'My first kill'},
	{text: 'Nunchuck moves'},
	{text: 'Oncoming traffic'},
	{text: 'One Ring to rule them all'},
	{text: 'Power'},
	{text: 'Pretty Pretty Princess Dress-Up Board Game®'},
	{text: 'Pumping out a baby every nine months'},
	{text: 'Rising from the grave'},
	{text: 'Scrotal frostbite'},
	{text: 'Some really fucked-up shit'},
	{text: 'Special musical guest, Cher'},
	{text: 'Spring break!'},
	{text: 'Subduing a grizzly bear and making her your wife'},
	{text: 'Survivor\'s guilt'},
	{text: 'Swiftly achieving orgasm'},
	{text: 'Taking a man\'s eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes'},
	{text: 'The corporations'},
	{text: 'The day the birds attacked'},
	{text: 'The Google'},
	// 'The grey nutrient broth that sustains Mitt Romney',
	{text: 'The human body'},
	// 'The mere concept of Applebee\'s®',
	{text: 'The mixing of the races'},
	{text: 'The new Radiohead album'},
	{text: 'Tiny nipples'},
	{text: 'Tongue'},
	{text: 'Upgrading homeless people to mobile hotspots'},
	{text: 'Weapons-grade plutonium'},
	{text: 'Wearing an octopus for a hat'},
	{text: 'Whining like a little bitch'},
	{text: 'Whipping a disobedient slave'}
];