module.exports = [
	{text: "How did I lose my virginity? %s", pick: 1},
	{text: "Why can't I sleep at night? %s", pick: 1},
	{text: "What's that smell? %s", pick: 1},
	{text: "I got 99 problems but %s ain't one.", pick: 1},
	{text: "Maybe she's born with it. Maybe it's %s.", pick: 1},
	{text: "What's the next Happy Meal toy? %s", pick: 1},
	{text: "Here is the church,\\Here is the steeple,\\Open the doors and there is %s.", pick: 1},
	{text: "It's a pity that kids these days are all involved with %s.", pick: 1},
	{text: "During his childhood, Salvador Dali produced hundreds of paintings of %s.", pick: 1},
	{text: "Alternative medicine is now embracing the curative powers of %s.", pick: 1},
	{text: "And the Academy Award for %s goes to %s2.", pick: 2},
	{text: "What's that sound? %s", pick: 1},
	{text: "What ended my last relationship? %s", pick: 1},
	{text: "MTV's new reality show features eight washed-up celebrities living with %s.", pick: 1},
	{text: "I drink to forget %s.", pick: 1},
	{text: "I'm sorry professor, but I couldn't complete my homework because of %s.", pick: 1},
	{text: "What is Batman's guilty pleasure? %s", pick: 1},
	{text: "This is the way the world ends\\This is the way the world ends\\Not with a bang but with %s.", pick: 1},
	{text: "What's a girls best friend? %s", pick: 1},
	{text: "TSA guidelines now prohibit %s on airplanes.", pick: 1},

	{text: "%s. That's how I want to die.", pick: 1},
	{text: "For my next trick, I will pull %s out of %s2.", pick: 2},
	{text: "In the new Disney Channel Original Movie, Hannah Montana struggles with %s for the first time.", pick: 1},
	{text: "%s is a slippery slope that leads to %s2.", pick: 2},
	// {text: "What does Dick Cheney prefer?  %s", pick: 1},
	{text: "Dear Abby, I'm having some trouble with %s and would like your advice.", pick: 1},
	{text: "Instead of coal, santa now gives the bad children %s.", pick: 1},
	{text: "What's the most emo? %s", pick: 1},
	{text: "In 1,000 years, when paper money is a distant memory, how will we pay for goods and services? %s", pick: 1},
	{text: "What's the next superhero/sidekick duo? %s and %s2", pick: 2},
	{text: "In M. Night Shyamalan's new movie, Bruce Willis discovers that %s had really been %s2 all along.", pick: 2},
	{text: "A romantic, candlelit dinner would be incomplete without %s.", pick: 1},
	{text: "%s. Betcha can't just have one!", pick: 1},
	{text: "White people like %s.", pick: 1},
	{text: "%s. High five, bro.", pick: 1},
	{text: "Next from J.K. Rowling: Harry Potter and the Chamber of %s.", pick: 1},
	{text: "BILLY MAYS HERE FOR %s.", pick: 1},
	{text: "In a world ravaged by %s our only solace is %s2.", pick: 2},
	{text: "War! What is it good for? %s", pick: 1},
	{text: "During sex, I like to think about %s.", pick: 1},

	{text: "What are my parents hiding from me? %s", pick: 1},
	{text: "What will always get you laid? %s", pick: 1},
	{text: "in L.A. County Jail, word is you can trade 200 cigarettes for %s.", pick: 1},
	{text: "What did I bring back from Mexico? %s", pick: 1},
	{text: "What don't you want to find in your Kung Pao chicken? %s", pick: 1},
	{text: "What will I bring back in time to convince people that I am a powerful wizard? %s", pick: 1},
	{text: "How am I maintaining my relationship status? %s", pick: 1},
	{text: "%s. It's a trap!", pick: 1},
	{text: "Coming to Broadway this season, %s: The Musical.", pick: 1},
	{text: "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on %s.", pick: 1},
	{text: "After the earthquake, Sean Penn brought %s to the people of Haiti.", pick: 1},
	{text: "Next on ESPN2, the World Series of %s.", pick: 1},
	{text: "Step 1: %s.\\Step 2: %s2.\\Step 3: Profit", pick: 2},
	{text: "Rumor has it that Vladimir Putin's favorite delicacy is %s stuffed with %s2.", pick: 2},
	{text: "Before I kill you, Mr Bond, I must show you %s.", pick: 1},
	{text: "What gives me uncontrollable gas? %s", pick: 1},
	{text: "What do old people smell like? %s", pick: 1},
	{text: "The class field trip was completely ruined by %s.", pick: 1},
	{text: "When Pharoh remained unmoved, Moses called down a plague of %s.", pick: 1},
	{text: "What's my secret power? %s", pick: 1},
	
	{text: "What's there a ton of in heaven? %s", pick: 1},
	{text: "What would grandma find disturbing, yet oddly charming? %s", pick: 1},
	{text: "I never truly understood %s until I encountered %s2.", pick: 2},
	{text: "What did the U.S. airdrop to the children of Afghanistan? %s", pick: 1},
	{text: "What helps Obama unwind? %s", pick: 1},
	{text: "What did Vin Diesel eat for dinner? %s", pick: 1},
	{text: "%s: good to the last drop.", pick: 1},
	{text: "Why am I sticky? %s", pick: 1},
	{text: "What gets better with age? %s", pick: 1},
	{text: "%s: kid-tested, mother-approved.", pick: 1},
	{text: "Daddy, why is mommy crying? %s", pick: 1},
	// {text: "What's Teach for America using to inspire inner city students to succeed? %s", pick: 1},
	{text: "Studies show that lab rats navigate mazes 50% faster after being exposed to %s.", pick: 1},
	{text: "Life for American Indians was forever changed when the White Man introduced them to %s.", pick: 1},
	{text: "I do not know what weapons World War III will be fought with, but World War IV will be fought with %s.", pick: 1},
	{text: "Why do I hurt all over? %s", pick: 1},
	{text: "What am I giving up for Lent? %s", pick: 1},
	{text: "In Michael Jackson's final moments, he thought about %s.", pick: 1},
	{text: "The Smithsonian Museum of Natural History has just opened an interactive exhibit on %s.", pick: 1},
	{text: "When I am the President of the United States, I will create the Department of %s.", pick: 1},
	{text: "Lifetime presents %s, the story of %s2.", pick: 2},
	{text: "When I am a billionaire, I shall erect a 50-foot statue to commemorate %s.", pick: 1},
	{text: "When I was tripping on acid, %s turned into %s2.", pick: 2},
	{text: "that's right, I killed %s. How, you ask? %s2", pick: 2},
	{text: "What's my anti-drug? %s", pick: 1},
	{text: "%s + %s2 = %s3", pick: 3, draw: 2},
	{text: "What never fails to liven up the party? %s", pick: 1},
	{text: "What's the new fad diet? %s", pick: 1},
	{text: "Major League Baseball has banned %s for giving players an unfair advantage.", pick: 1},
	
];