module.exports = [
	{text: '50,000 volts straight to the nipples'},
	{text: '72 virgins'},
	{text: '8 oz. of sweet Mexican black-tar heroin'},
	{text: 'A bag of magic beans'},
	{text: 'A balanced breakfast'},
	{text: 'A bitch slap'},
	{text: 'A bleached asshole'},
	// {text: 'A Bop It™'},
	{text: 'A brain tumor'},
	{text: 'A bucket of fish heads'},
	{text: 'A can of whoop-ass'},
	{text: 'A cooler full of organs'},
	{text: 'A death ray'},
	{text: 'A defective condom'},
	{text: 'A disappointing birthday party'},
	{text: 'A falcon with a cap on its head'},
	{text: 'A fetus'},
	{text: 'A foul mouth'},
	{text: 'A gassy antelope'},
	{text: 'A gentle caress of the inner thigh'},
	{text: 'A good sniff'},
	{text: 'A homoerotic volleyball montage'},
	{text: 'A hot mess'},
	{text: 'A lifetime of sadness'},
	{text: 'A live studio audience'},
	{text: 'A mating display'},
	{text: 'A micropenis'},
	{text: 'A micropig wearing a tiny raincoat and booties'},
	{text: 'A middle-aged man on roller skates'},
	{text: 'A mime having a stroke'},
	{text: 'A monkey smoking a cigar'},
	{text: 'A mopey zoo lion'},
	{text: 'A murder most foul'},
	{text: 'A pyramid of severed heads'},
	{text: 'A really cool hat'},
	{text: 'A robust mongoloid'},
	{text: 'A sad handjob'},
	{text: 'A salty surprise'},
	{text: 'A sassy black woman'},
	{text: 'A sausage festival'},
	{text: 'A sea of troubles'},
	{text: 'A snapping turtle biting the tip of your penis'},
	{text: 'A spastic nerd'},
	{text: 'A stray pube'},
	{text: 'A subscription to Men\'s Fitness'},
	{text: 'A Super Soaker™ full of cat pee'},
	{text: 'A thermonuclear detonation'},
	{text: 'A time travel paradox'},
	{text: 'A tiny horse'},
	{text: 'A tribe of warrior women'},
	{text: 'A windmill full of corpses'},
	{text: 'A zesty breakfast burrito'},
	// {text: 'Aaron Burr'},
	{text: 'Active listening'},
	{text: 'Actually taking candy from a baby'},
	// {text: 'Adderall™'},
	{text: 'Advice from a wise, old black man'},
	{text: 'African children'},
	{text: 'Agriculture'},
	{text: 'AIDS'},
	{text: 'Alcoholism'},
	{text: 'All-you-can-eat shrimp for $4.99'},
	{text: 'Altar boys'},
	{text: 'Amputees'},
	{text: 'An asymmetric boob job'},
	{text: 'An erection that lasts longer than four hours'},
	{text: 'An icepick lobotomy'},
	{text: 'An M. Night Shyamalan plot twist'},
	{text: 'An M16 assault rifle'},
	// {text: 'An Oedipus complex'},
	{text: 'An oversized lollipop'},
	{text: 'An ugly face'},
	{text: 'An uppercut'},
	{text: 'Anal beads'},
	{text: 'Another goddamn vampire movie'},
	{text: 'Arnold Schwarzenegger'},
	{text: 'Asians who aren\'t good at math'},
	{text: 'Assless chaps'},
	{text: 'Attitude'},
	{text: 'Auschwitz'},
	{text: 'Authentic Mexican cuisine'},
	{text: 'Autocannibalism'},
	{text: 'AXE Body Spray'},
	{text: 'Balls'},
	{text: 'Barack Obama'},
	{text: 'BATMAN!!!'},
	{text: 'Battlefield amputations'},
	{text: 'Bees?'},
	{text: 'Being a dick to children'},
	{text: 'Being a motherfucking sorcerer'},
	{text: 'Being fabulous'},
	{text: 'Being fat and stupid'},
	{text: 'Being marginalized'},
	{text: 'Being on fire'},
	{text: 'Being rich'},
	{text: 'Bill Nye the Science Guy'},
	{text: 'Bingeing and purging'},
	{text: 'Bitches'},
	{text: 'Black people'},
	{text: 'Bling'},
	{text: 'Boogers'},
	{text: 'Breaking out into song and dance'},
	{text: 'Britney Spears at 55'},
	{text: 'Brown people'},
	// {text: 'Capturing Newt Gingrich and forcing him to dance in a monkey suit'},
	{text: 'Cards Against Humanity'},
	{text: 'Catapults'},
	{text: 'Centaurs'},
	{text: 'Chainsaws for hands'},
	{text: 'Cheating in the Special Olympics'},
	{text: 'Child beauty pageants'},
	{text: 'Children on leashes'},
	{text: 'Christopher Walken'},
	{text: 'Chunks of dead prostitute'},
	{text: 'Civilian casualties'},
	{text: 'Classist undertones'},
	{text: 'Coat hanger abortions'},
	{text: 'Concealing a boner'},
	{text: 'Consensual sex'},
	{text: 'Copping a feel'},
	{text: 'Count Chocula'},
	{text: 'Crippling debt'},
	{text: 'Crucifixion'},
	{text: 'Crystal meth'},
	{text: 'Cuddling'},
	{text: 'Cybernetic enhancements'},
	{text: 'Daddy issues'},
	{text: 'Darth Vader'},
	{text: 'Dead babies'},
	{text: 'Dead parents'},
	{text: 'Dental dams'},
	{text: 'Destroying the evidence'},
	// {text: 'Dick Cheney'},
	{text: 'Dick fingers'},
	{text: 'Doin\' it in the butt'},
	{text: 'Doing the right thing'},
	// {text: 'Domino\'s™ Oreo™ Dessert Pizza'},
	{text: 'Drinking alone'},
	{text: 'Dropping a chandelier on your enemies and riding the rope up'},
	{text: 'Dry heaving'},
	{text: 'Dying of dysentery'},
	{text: 'Dying'},
	{text: 'Eating all of the cookies before the AIDS bake-sale'},
	{text: 'Eating the last known bison'},
	{text: 'Edible underpants'},
	{text: 'Elderly Japanese men'},
	{text: 'Embryonic stem cells'},
	{text: 'Emotions'},
	{text: 'Erectile dysfunction'},
	{text: 'Estrogen'},
	{text: 'Ethnic cleansing'},
	{text: 'Eugenics'},
	{text: 'Exactly what you\'d expect'},
	{text: 'Expecting a burp and vomiting on the floor'},
	{text: 'Explosions'},
	{text: 'Extremely tight pants'},
	{text: 'Famine'},
	// {text: 'Fancy Feast®'},
	{text: 'Farting and walking away'},
	{text: 'Fear itself'},
	// {text: 'Feeding Rosie O\'Donnell'},
	{text: 'Fiery poops'},
	{text: 'Figgy pudding'},
	{text: 'Finger painting'},
	{text: 'Fingering'},
	{text: 'Firing a rifle into the air while balls deep in a squealing hog'},
	// {text: 'Five-Dollar Footlongs™'},
	{text: 'Flesh-eating bacteria'},
	{text: 'Flightless birds'},
	{text: 'Flying sex snakes'},
	{text: 'Foreskin'},
	{text: 'Former President George W. Bush'},
	{text: 'Free samples'},
	{text: 'Friction'},
	{text: 'Friendly fire'},
	{text: 'Friends with benefits'},
	{text: 'Frolicking'},
	{text: 'Full frontal nudity'},
	{text: 'Funky fresh rhymes'},
	{text: 'Gandhi'},
	{text: 'Geese'},
	{text: 'Genghis Khan'},
	{text: 'Genital piercings'},
	{text: 'German dungeon porn'},
	{text: 'Getting drunk on mouthwash'},
	{text: 'Getting married, having a few kids, buying some stuff, retiring to Florida, and dying'},
	{text: 'Getting naked and watching Nickelodeon'},
	{text: 'Getting really high'},
	{text: 'Getting so angry that you pop a boner'},
	{text: 'Ghosts'},
	{text: 'Giving 110%'},
	{text: 'Gloryholes'},
	{text: 'Goblins'},
	{text: 'God'},
	// {text: 'GoGurt®'},
	{text: 'Golden showers'},
	{text: 'Grandma'},
	{text: 'Grave robbing'},
	{text: 'Growing a pair'},
	{text: 'Guys who don\'t call'},
	{text: 'Half-assed foreplay'},
	{text: 'Harry Potter erotica'},
	{text: 'Heartwarming orphans'},
	{text: 'Helplessly giggling at the mention of Hutus and Tutsis'},
	{text: 'Her Majesty, Queen Elizabeth II'},
	{text: 'Heteronormativity'},
	{text: 'Historically black colleges'},
	{text: 'Home video of Oprah sobbing into a Lean Cuisine®'},
	{text: 'Homeless people'},
	{text: 'Hope'},
	{text: 'Hormone injections'},
	{text: 'Horrifying laser hair removal accidents'},
	{text: 'Horse meat'},
	{text: 'Hospice care'},
	{text: 'Hot cheese'},
	{text: 'Hot people'},
	{text: 'Hot Pockets®'},
	{text: 'Hulk Hogan'},
	{text: 'Hurricane Katrina'},
	{text: 'Inappropriate yodeling'},
	{text: 'Incest'},
	{text: 'Italians'},
	{text: 'Jerking off into a pool of children\'s tears'},
	{text: 'Jewish fraternities'},
	{text: 'John Wilkes Booth'},
	{text: 'Judge Judy'},
	{text: 'Justin Bieber'},
	{text: 'Kamikaze pilots'},
	{text: 'Kanye West'},
	{text: 'Keanu Reeves'},
	{text: 'Kids with ass cancer'},
	{text: 'Lactation'},
	{text: 'Lady Gaga'},
	// {text: 'Lance Armstrong\'s missing testicle'},
	{text: 'Land mines'},
	{text: 'Laying an egg'},
	{text: 'Leaving an awkward voicemail'},
	{text: 'Leprosy'},
	{text: 'Licking things to claim them as your own'},
	{text: 'Lockjaw'},
	{text: 'Lumberjack fantasies'},
	// {text: 'Lunchables™'},
	{text: 'Making a pouty face'},
	{text: 'Man meat'},
	{text: 'Masturbation'},
	{text: 'Me time'},
	{text: 'MechaHitler'},
	{text: 'Men'},
	{text: 'Menstrual rage'},
	{text: 'Michael Jackson'},
	{text: 'Michelle Obama\'s arms'},
	{text: 'Morgan Freeman\'s voice'},
	{text: 'Mouth herpes'},
	// {text: 'Mr. Clean, right behind you'},
	{text: 'Muhammed (Praise Be Unto Him)'},
	{text: 'Multiple stab wounds'},
	{text: 'Mutually-assured destruction'},
	{text: 'My collection of high-tech sex toys'},
	{text: 'My genitals'},
	{text: 'My humps'},
	{text: 'My inner demons'},
	{text: 'My relationship status'},
	{text: 'My sex life'},
	{text: 'My soul'},
	{text: 'My vagina'},
	{text: 'Natalie Portman'},
	{text: 'Natural male enhancement'},
	{text: 'Natural selection'},
	{text: 'Nazis'},
	{text: 'Necrophilia'},
	{text: 'New Age music'},
	{text: 'Nickelback'},
	{text: 'Nicolas Cage'},
	{text: 'Nipple blades'},
	{text: 'Not giving a shit about the Third World'},
	{text: 'Not reciprocating oral sex'},
	{text: 'Not wearing pants'},
	{text: 'Obesity'},
	{text: 'Object permanence'},
	{text: 'Old-people smell'},
	{text: 'One trillion dollars'},
	{text: 'Oompa-Loompas'},
	{text: 'Opposable thumbs'},
	{text: 'Overcompensation'},
	// {text: 'Pabst Blue Ribbon'},
	{text: 'Pac-Man uncontrollably guzzling cum'},
	{text: 'Panda sex'},
	{text: 'Parting the Red Sea'},
	{text: 'Passable transvestites'},
	{text: 'Passing a kidney stone'},
	{text: 'Passive-aggressive Post-it notes'},
	{text: 'Passive-agression'},
	{text: 'Pedophiles'},
	{text: 'Peeing a little bit'},
	{text: 'Penis envy'},
	{text: 'Picking up girls at the abortion clinic'},
	{text: 'Pictures of boobs'},
	{text: 'Pixelated bukkake'},
	{text: 'Police brutality'},
	{text: 'Pooping back and forth. Forever'},
	{text: 'Poopy diapers'},
	{text: 'Poor life choices'},
	{text: 'Poor people'},
	{text: 'Poorly-timed Holocaust jokes'},
	{text: 'Porn stars'},
	{text: 'Powerful thighs'},
	{text: 'Prancing'},
	{text: 'Praying the gay away'},
	{text: 'Preteens'},
	{text: 'Pretending to care'},
	{text: 'Puberty'},
	{text: 'Public ridicule'},
	{text: 'Pulling out'},
	{text: 'Puppies!'},
	{text: 'Queefing'},
	// {text: 'Racially-biased SAT questions'},
	{text: 'Racism'},
	{text: 'Raptor attacks'},
	{text: 'Rehab'},
	{text: 'Repression'},
	{text: 'Republicans'},
	{text: 'Riding off into the sunset'},
	{text: 'Road head'},
	{text: 'Robert Downey, Jr'},
	{text: 'RoboCop'},
	{text: 'Ronald Reagan'},
	{text: 'Roofies'},
	// {text: 'Rush Limbaugh\'s soft, shitty body'},
	{text: 'Same-sex ice dancing'},
	{text: 'Sarah Palin'},
	{text: 'Saxophone solos'},
	{text: 'Scalping'},
	{text: 'Science'},
	{text: 'Scientology'},
	{text: 'Scrubbing under the folds'},
	{text: 'Sean Connery'},
	{text: 'Sean Penn'},
	{text: 'Self-loathing'},
	// {text: 'Seppuku'},
	// {text: 'Serfdom'},
	{text: 'Sexting'},
	{text: 'Sexual tension'},
	{text: 'Sexy pillow fights'},
	{text: 'Shapeshifters'},
	{text: 'Shaquille O\'Neal\'s acting career'},
	{text: 'Sharing needles'},
	{text: 'Shiny objects'},
	{text: 'Silence'},
	{text: 'Skeletor'},
	{text: 'Smallpox blankets'},
	{text: 'Smegma'},
	{text: 'Sniffing glue'},
	{text: 'Some god-damn peace and quiet'},
	{text: 'Soup that is too hot'},
	{text: 'Spectacular abs'},
	{text: 'Sperm whales'},
	{text: 'Spontaneous human combustion'},
	{text: 'Stalin'},
	{text: 'Stephen Hawking talking dirty'},
	{text: 'Stormtroopers'},
	{text: 'Stranger danger'},
	{text: 'Sunshine and rainbows'},
	{text: 'Surprise sex!'},
	{text: 'Sweet, sweet vengeance'},
	// {text: 'Switching to Geico®'},
	{text: 'Swooping'},
	{text: 'Synergistic management solutions'},
	{text: 'Take-backsies'},
	{text: 'Taking off your shirt'},
	{text: 'Tangled Slinkys'},
	{text: 'Tasteful sideboob'},
	{text: 'Teaching a robot to love'},
	{text: 'Teenage pregnancy'},
	{text: 'Tentacle porn'},
	{text: 'Testicular torsion'},
	{text: 'That thing that electrocutes your abs'},
	{text: 'The American Dream'},
	{text: 'The Amish'},
	{text: 'The art of seduction'},
	{text: 'The Big Bang'},
	{text: 'The Blood of Christ'},
	{text: 'The Boy Scouts of America'},
	{text: 'The Care Bear Stare'},
	{text: 'The Chinese gymnastics team'},
	{text: 'The chronic'},
	{text: 'The clitoris'},
	{text: 'The Dance of the Sugar Plum Fairy'},
	{text: 'The Devil himself'},
	{text: 'The entire Mormon Tabernacle Choir'},
	{text: 'The female orgasm'},
	{text: 'The folly of man'},
	{text: 'The Force'},
	{text: 'The gays'},
	{text: 'The glass ceiling'},
	{text: 'The Great Depression'},
	{text: 'The Hamburglar'},
	{text: 'The hardworking Mexican'},
	{text: 'The heart of a child'},
	{text: 'The Holy Bible'},
	{text: 'The homosexual agenda'},
	{text: 'The Hustle'},
	{text: 'The inevitable heat death of the universe'},
	{text: 'The invisible hand'},
	{text: 'The Jews'},
	{text: 'The KKK'},
	{text: 'The Kool-Aid Man'},
	{text: 'The light of a billion suns'},
	{text: 'The Little Engine That Could'},
	{text: 'The Make-A-Wish® Foundation'},
	{text: 'The milk man'},
	{text: 'The miracle of childbirth'},
	// {text: 'The penny whistle solo from "My Heart Will Go On."'},
	{text: 'The placenta'},
	{text: 'The Pope'},
	{text: 'The profoundly handicapped'},
	{text: 'The Rapture'},
	{text: 'The Rev. Dr. Martin Luther King, Jr'},
	{text: 'The South'},
	{text: 'The taint; the grundle; the fleshy fun-bridge'},
	// {text: 'The Tempur-Pedic® Swedish Sleep System™'},
	{text: 'The terrorists'},
	{text: 'The Three-Fifths compromise'},
	{text: 'The token minority'},
	{text: 'The Trail of Tears'},
	{text: 'The true meaning of Christmas'},
	{text: 'The Underground Railroad'},
	{text: 'The violation of our most basic human rights'},
	{text: 'The Virginia Tech Massacre'},
	{text: 'The World of Warcraft'},
	{text: 'The Übermensch'},
	{text: 'Third base'},
	{text: 'Throwing a virgin into a volcano'},
	// {text: 'Tickling Sean Hannity, even after he tells you to stop'},
	{text: 'Tom Cruise'},
	// {text: 'Toni Morrison\'s vagina'},
	{text: 'Two midgets shitting into a bucket'},
	{text: 'Unfathomable stupidity'},
	{text: 'Used panties'},
	{text: 'Vehicular manslaughter'},
	{text: 'Viagra®'},
	{text: 'Vigilante justice'},
	{text: 'Vigorous jazz hands'},
	{text: 'Vikings'},
	{text: 'Waiting \'til marriage'},
	{text: 'Waking up half-naked in a Denny\'s parking lot'},
	{text: 'Wearing underwear inside-out to avoid doing laundry'},
	{text: 'Wet dreams'},
	{text: 'When you fart and a little bit comes out'},
	{text: 'Whipping it out'},
	{text: 'White people'},
	{text: 'White privilege'},
	{text: 'Wifely duties'},
	{text: 'William Shatner'},
	{text: 'Winking at old people'},
	{text: 'Wiping her butt'},
	{text: 'Women in yogurt commercials'},
	{text: 'Women\'s suffrage'},
	{text: 'World peace'},
	{text: 'Yeast'},
	{text: 'YOU MUST CONSTRUCT ADDITIONAL PYLONS'}
];