module.exports = [
	{text: "In the seventh circle of Hell, sinners must endure %s for all eternity.", pick: 1},
	{text: "A successful job interview begins with a firm handshake and ends with %s.", pick: 1},
	{text: "Lovin’ you is easy ’cause you’re %s.", pick: 1},
	{text: "My life is ruled by a vicious cycle of %s and %s2.", pick: 2},
	{text: "The blind date was going horribly until we discovered our shared interest in %s.", pick: 1},
	{text: "%s. Awesome in theory, kind of a mess in practice.", pick: 1},
	{text: "I’m not like the rest of you. I’m too rich and busy for %s.", pick: 1},
	{text: "%s: Hours of fun. Easy to use. Perfect for %s2!", pick: 2},
	{text: "What left this stain on my couch? %s", pick: 1},
	{text: "Call the law offices of Goldstein & Goldstein, because no one should have to tolerate %s in the workplace.", pick: 1},
	{text: "When you get right down to it, %s is just %s2.", pick: 2},
	{text: "Turns out that %s-Man was neither the hero we needed nor wanted.", pick: 1},
	{text: "As part of his daily regimen, Anderson Cooper sets aside 15 minutes for %s.", pick: 1},
	{text: "Money can’t buy me love, but it can buy me %s.", pick: 1},
	{text: "With enough time and pressure, %s will turn into %s2.", pick: 2},
	{text: "And what did you bring for show and tell? %s", pick: 1},
	{text: "During high school I never really fit in until I found %s club.", pick: 1},
	{text: "Hey baby, come back to my place and I’ll show you %s.", pick: 1},
	{text: "After months of practice with %s, I think I’m finally ready for %s2.", pick: 2},
	{text: "To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of %s.", pick: 1},
	{text: "Finally! A service that delivers %s right to your door.", pick: 1},
	{text: "My gym teacher got fired for adding %s to the obstacle course.", pick: 1},
	{text: "Having problems with %s? Try %s2!", pick: 2},
	{text: "As part of his contract, Prince won’t perform without %s in his dressing room.", pick: 1},
	{text: "Listen, son. If you want to get involved with %s, I won’t stop you. Just steer clear of %s2.", pick: 2}
];