module.exports = [
	{text: "%s? Ten-outta-ten!", pick: 1},
	{text: "AND YOU THINK THAT OF ME?\\I AM THE ONE WHO IS %s", pick: 1},
	{text: "Yeah! %s, bitch!", pick: 1},
	{text: "WHERE IS HE? %s", pick: 1},
	{text: "You’re an insane, degenerate piece of filth, and you deserve %s", pick: 1},
	{text: "Say my name. %s", pick: 1},
	{text: "%s has to be at least... three times bigger than this!", pick: 1},
	{text: "%s. 60% of the time, it works every time.", pick: 1},
	{text: "But can you do %s in 100!!! browser windows????", pick: 1},
	{text: "Hey kid! I'm %s", pick: 1},
	// {text: "WHAT IS THIS?? %s? IT NEEDS TO BE.. %s2!", pick: 2},
	{text: "Argh! Right in the %s!", pick: 1},
	{text: "Your mommas so fat, she's %s!", pick: 1},
	{text: "%s... if you know what I mean.", pick: 1},
	{text: "I can't believe you've done %s", pick: 1},
	{text: "Mmm smells like %s", pick: 1},
	// {text: "But I %s from there!", pick: 1},
	{text: "Looks like this %s just got turned into a %s2", pick: 2},
	{text: "Brick.. you killed a guy with %s.", pick: 1},
	{text: "The newly developed engine is fueled by %s.", pick: 1},
	{text: "Who you gonna call? %s", pick: 1},
	{text: "All these %s man.", pick: 1},
	{text: "Give him the %s. DON'T give him the %s!", pick: 2},
	{text: "Na na na na na na na na na %s-man!", pick: 1},
	{text: "It Rubs %s on its skin or it gets %s again.", pick: 2},
	{text: "%s vs. %s: The new SyFy original movie.", pick: 2},
	{text: "One small step for man, one giant leap for %s.", pick: 1},
	{text: "Bitches love %s.", pick: 1},
	{text: "%s isn't exactly rocket appliances.", pick: 1},
];