module.exports = [
	{text: 'A face like a bucket of smashed crabs'},
	{text: 'A CENTER FOR ANTS'},
	{text: 'Smells like Bigfoot\'s dick!'},
	{text: 'Robots?'},
	{text: 'A computer'},
	{text: 'All the downloadin!'},
	{text: 'Fallopian tube spaghetti'},
	{text: 'A Ham Planet'},
	{text: 'Menstruation mouthwash'},
	{text: 'A ghost chip'},
	{text: 'SHUT THE FUCK UP'},
	{text: 'I love lamp'},
	{text: 'A coathanger attached to a vacuum cleaner'},
	{text: 'LOUD NOISES'},
	{text: 'Sticking a midget to a fat person with super glue'},
	{text: 'Hairy Boobs'},
	{text: 'Pepperoni nips'},
	{text: 'Ghost Mustard'},
	{text: 'Laddergoat'},
	{text: '420'},
	{text: 'Dildos at the dinner table'},
	{text: 'Deleting the nudes'}
];