module.exports = [
	{text: 'An immediately regrettable $9 hot dog from the Boston Convention Center'},
	{text: 'Running out of stamina'},
	{text: 'Casting Magic Missle at a bully'},
	{text: 'Getting bitch slapped by Dhalsim'},
	{text: 'Firefly: Season 2'},
	{text: 'Rotating shapes in mid-air so that they fit into other shapes when they fall'},
	{text: 'Jiggle physics'},
	{text: 'Paying the iron price'},
	{text: 'Loading from a previous save'},
	{text: 'Sharpening a foam broadsword on a foam whetstone'},
	{text: 'The rocket launcher'},
	{text: 'The depression that ensues after catching ‘em all'},
	{text: 'Violating the First Law of Robotics'},
	{text: 'Getting inside the Horadric Cube with a hot babe and pressing the transmute button'},
	{text: 'Punching a tree to gather wood'},
	{text: 'Spending the year’s insulin budget on Warhammer 40k figurines'},
	{text: 'Achieving 500 actions per minute'},
	{text: 'Forgetting to eat, and consequently dying'},
	{text: 'Wil Wheaton crashing an actual spaceship'},
	{text: 'The Klobb'},
	{text: 'Charging up all the way'},
	{text: 'Vespene gas'},
	{text: 'Judging elves by the color of their skin and not by the content of their character'},
	{text: 'Smashing all the pottery in a Pottery Barn in search of rupees'}
];