module.exports = [
	{text: "An international tribunal has found %s guilty of %s2.", pick: 2},
	{text: "And I would have gotten away with it, too, if it hadn't been for %s!", pick: 1},
	{text: "Dear Sir or Madam, We regret to inform you that the Office of %s has denied your request for %s2.", pick: 2},
	{text: "He who controls %s controls the world.", pick: 1},
	{text: "I learned the hard way that you can't cheer up a grieving friend with %s.", pick: 1},
	{text: "In a pinch, %s can be a suitable substitute for %s2.", pick: 2},
	{text: "In his new self-produced album, Kanye West raps over the sounds of %s.", pick: 1},
	{text: "In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated %s.", pick: 1},
	{text: "In Rome, there are whisperings that the Vatican has a secret room devoted to %s.", pick: 1},
	{text: "In the distant future, historians will agree that %s marked the beginning of America's decline.", pick: 1},
	{text: "Michael Bay's new three-hour action epic pits %s against %s2.", pick: 2},
	{text: "Science will never explain the origin of %s.", pick: 1},
	{text: "The CIA now interrogates enemy agents by repeatedly subjecting them to %s.", pick: 1},
	{text: "The socialist governments of Scandinavia have declared that access to %s is a basic human right.", pick: 1},
	{text: "This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only %s and his wits.", pick: 1},
	{text: "What brought the orgy to a grinding halt? %s", pick: 1},
	{text: "What has been making life difficult at the nudist colony? %s", pick: 1},
	{text: "What's the gift that keeps on giving? %s", pick: 1},
	{text: "When all else fails, I can always masturbate to %s.", pick: 1},
	{text: "When I pooped, what came out of my butt? %s", pick: 1},
];