module.exports = [
	{text: 'A beached whale'},
	{text: 'A big black dick'},
	{text: 'A bloody pacifier'},
	{text: 'A crappy little hand'},
	{text: 'A low standard of living'},
	{text: 'A nuanced critique'},
	{text: 'A passionate Latino lover'},
	{text: 'A rival dojo'},
	{text: 'A web of lies'},
	{text: 'A woman scorned'},
	{text: 'Apologizing'},
	{text: 'Appreciative snapping'},
	{text: 'Beating your wives'},
	{text: 'Being a busy adult with many important things to do'},
	{text: 'Being a dinosaur'},
	{text: 'Bosnian chicken farmers'},
	{text: 'Carnies'},
	{text: 'Clams'},
	{text: 'Coughing into a vagina'},
	{text: 'Dancing with a broom'},
	{text: 'Deflowering the princess'},
	{text: 'Dorito breath'},
	{text: 'Eating an albino'},
	{text: 'Enormous Scandinavian women'},
	{text: 'Fabricating statistics'},
	{text: 'Finding a skeleton'},
	{text: 'Gandalf'},
	{text: 'Genetically engineered super-soldiers'},
	{text: 'George Clooney\'s musk'},
	{text: 'Getting abducted by Peter Pan'},
	{text: 'Getting in her pants, politely'},
	{text: 'Gladiatorial combat'},
	{text: 'Good grammar'},
	{text: 'Hipsters'},
	{text: 'Historical revisionism'},
	{text: 'Insatiable bloodlust'},
	{text: 'Jafar'},
	{text: 'Jean-Claude Van Damme'},
	{text: 'Just the tip'},
	{text: 'Leveling up'},
	{text: 'Literally eating shit'},
	{text: 'Mad hacky-sack skills'},
	{text: 'Making the penises kiss'},
	{text: 'Media coverage'},
	{text: 'Medieval Times® Dinner & Tournament'},
	{text: 'Moral ambiguity'},
	{text: 'My machete'},
	{text: 'Neil Patrick Harris'},
	{text: 'Nubile slave boys'},
	{text: 'Ominous background music'},
	{text: 'One thousand Slim Jims'},
	{text: 'Overpowering your father'},
	{text: 'Panty raids'},
	{text: 'Pistol-whipping a hostage'},
	{text: 'Quiche'},
	{text: 'Quivering jowls'},
	{text: 'Revenge fucking'},
	{text: 'Ripping into a man\'s chest and pulling out his still-beating heart'},
	{text: 'Ryan Gosling riding in on a white horse'},
	{text: 'Santa Claus'},
	{text: 'Scrotum tickling'},
	{text: 'Sexual humiliation'},
	{text: 'Sexy Siamese twins'},
	{text: 'Shaft'},
	{text: 'Slow motion'},
	{text: 'Space muffins'},
	{text: 'Statistically validated stereotypes'},
	{text: 'Sudden Poop Explosion Disease'},
	{text: 'Suicidal thoughts'},
	{text: 'The boners of the elderly'},
	{text: 'The economy'},
	{text: 'The Fanta® girls'},
	{text: 'The four arms of Vishnu'},
	{text: 'The Gulags'},
	{text: 'The harsh light of day'},
	{text: 'The hiccups'},
	{text: 'The shambling corpse of Larry King'},
	{text: 'Tripping balls'},
	{text: 'Words, words, words'},
	{text: 'Zeus\'s sexual appetites'}
];